services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka-broker-1:
    container_name: kafka-broker-1
    image: docker.io/bitnami/kafka:3.8
    ports:
      - "9091:9091"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENERS: INTERNAL://:19091,EXTERNAL://:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-1:19091,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_CFG_SUPER_USERS: User:superuser
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:19091 || exit 1
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - zookeeper

  kafka-admin:
    container_name: kafka-admin
    image: docker.io/bitnami/kafka:3.8
    environment:
      KAFKA_CFG_NODE_ID: 9
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENERS: INTERNAL://:19099
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-admin:19099
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
    depends_on:
      kafka-broker-1:
        condition: service_healthy
    volumes:
      - ./create-kafka-user.sh:/docker-entrypoint-initdb.d/create-kafka-user.sh
    entrypoint: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/create-kafka-user.sh"]

