services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka-admin:
    container_name: kafka-admin
    image: docker.io/bitnami/kafka:3.8
    environment:
      KAFKA_CFG_NODE_ID: 9
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENERS: INTERNAL://:19099
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-admin:19099
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
    depends_on:
      - zookeeper
    volumes:
      - ./hello-world.sh:/docker-entrypoint-initdb.d/hello-world.sh
    entrypoint: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/hello-world.sh"]


  kafka-broker-1:
    container_name: kafka-broker-1
    image: docker.io/bitnami/kafka:3.8
    ports:
      - "9091:9091"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENERS: INTERNAL://:19091,EXTERNAL://:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-1:19091,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
    depends_on:
      - zookeeper

  # https://github.com/redpanda-data/console
  redpanda-data-console:
    container_name: redpanda-data-console
    image: docker.redpanda.com/redpandadata/console:v2.8.1
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-broker-1:19091"]
        sasl:
          enabled: false
          username: superuser
          password: secret
          mechanism: SCRAM-SHA-512
    depends_on:
      - kafka-broker-1
